#!/usr/bin/env sh

clear

cd ../cmt
make || exit
. setup.sh

cd ../apps
rm -f *.root
export PATH=../${CMTCONFIG}:${PATH}
   testGenerateData.exe \
&& testMakeCel.exe \
&& testReadCel.exe \
&& celInspect.exe test.cel.root \
&& celConvert.exe test.cel.root \
&& celRelocate.exe -r $HOME -a HOME test.cel.root \
&& celInspect.exe test.cel.root





