#!/usr/bin/env sh

clear

cd ../cmt
make binclean
find .. -name *rootcint*.h -exec rm \{\} \;
find .. -name *rootcint*.cxx -exec rm \{\} \;
make
. setup.sh

cd ../apps
rm -f *.root
export PATH=../${CMTCONFIG}:${PATH}
testWrite.exe && testRead.exe




