#!/usr/bin/env sh

clear

cmd="cel$1.exe"

cd ../cmt
make || exit
. setup.sh

cd ../apps
export PATH=../${CMTCONFIG}:${PATH}

if [ $1 != "Convert" -a $1 != "Inspect" ] ; then
  celInspect.exe test.cel.root
  echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
fi

$cmd test.cel.root

if [ $1 != "Convert" -a $1 != "Inspect" ] ; then
  celInspect.exe test.cel.root
  echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
fi




